---
- name: Create a volume group on top of /dev/sdb1 and resize the volume group /dev/sdb1 to the maximum possible
  lvg:
    vg: data
    pvs: /dev/sdb1

- name: Create a logical volume the size of all remaining space in the volume group
  lvol:
    vg: data
    lv: data_files
    size: 100%FREE

- name: Create a xfs filesystem on /dev/sdb1
  filesystem:
    fstype: xfs
   dev: /dev/data/data_files
    force: yes

- name: Create a /srv directory
  ansible.builtin.file:
    path: /srv/data
    state: directory


- name: Mount and bind a volume
  mount:
    path: /srv/data
    src: /dev/mapper/data-data_files
    state: mounted
    fstype: xfs 