---
gitlab_config_dir: "/srv/data/gitlab/config"
gitlab_logs_dir: "/srv/data/gitlab/logs"
gitlab_data_dir: "/srv/data/gitlab/data"
gitlab_image: "gitlab/gitlab-ce:latest"
gitlab_ssh_port: "2222"
gitlab_https_port: "127.0.0.1:10443"
gitlab_http_port: "127.0.0.1:10080"
gitlab_smtp_server: "mail.example.com"
gitlab_smtp_user: "gitlab@example.com"
gitlab_smtp_password: "mypassword"
gitlab_smtp_domain: "example.com"
gitlab_certs_folder: "/etc/certs/gitlab"
gitlab_dhparam_folder: "/etc/nginx/ssl/"
gitlab_site: "gitlab.irv.local"
gitlab_fullchain: "/etc/certs/gitlab/Gitlab.crt"
gitlab_cert_key: "/etc/certs/gitlab/Gitlab.key"