---
- name: Create Gitlab Directories
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
  loop:
    - "{{ gitlab_config_dir }}"
    - "{{ gitlab_logs_dir }}"
    - "{{ gitlab_data_dir }}"
    - "{{ gitlab_certs_folder }}"
    - "{{ gitlab_dhparam_folder }}"

- name: Install Nginx
  apt: 
    name: nginx 
    state: latest

- name: restart nginx
  service: 
    name: nginx 
    state: reloaded

- name: Install Gitlab container
  docker_container:
    name: gitlab
    image: "{{ gitlab_image }}"
    state: started
    ports:
      - "{{ gitlab_ssh_port }}:22"
      - "{{ gitlab_http_port }}:80"
      - "{{ gitlab_https_port }}:443"
    volumes:
      - "{{ gitlab_config_dir }}:/etc/gitlab"
      - "{{ gitlab_logs_dir }}:/var/log/gitlab"
      - "{{ gitlab_data_dir }}:/var/opt/gitlab"
    restart_policy: always    

- name: change gitlab external url
  replace: 
    dest: "{{ gitlab_config_dir }}/gitlab.rb" 
    regexp: "^# external_url" 
    replace: "external_url = 'https://{{ gitlab_site }}'" 

- name: deploy gitlab configuration
  template: 
    src: gitlab.rb.j2 
    dest: "{{ gitlab_config_dir }}/gitlab.rb" 
    owner: root 
    group: root 
    mode: 0644

- name: deploy certificates
  template: 
    src: "{{ item }}" 
    dest: "{{ gitlab_certs_folder }}" 
    owner: root 
    group: root 
    mode: 0644
  loop:
    - "Gitlab.crt"
    - "Gitlab.key"

- name: Create dhparam.pem
  shell: openssl dhparam -out /etc/nginx/ssl/dhparam.pem 4096

- name: deploy gitlab NGINX configuration
  template: 
    src: nginx.conf.j2 
    dest: /etc/nginx/sites-available/gitlab.conf 
    owner: root 
    group: root 
    mode: 0644    

- name: Enable gitlab NGINX configuration
  file: 
    src: /etc/nginx/sites-available/gitlab.conf 
    dest: /etc/nginx/sites-enabled/gitlab.conf 
    state: link    

- name: Restart NGINX
  service: 
    name: nginx 
    state: restarted    
    